name: End-to-end Tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  # Run e2e test against localnet built on the testnet branch
  localnet:
    name: Localnet
    runs-on: ubuntu-ghcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TS SDK e2e tests
        run: pnpm --filter @onelabs/sui test:e2e

      - name: Run RPC/GraphQL compatibility e2e tests
        run: pnpm --filter @onelabs/graphql-transport test:e2e

      - name: Run kiosk sdk e2e tests
        run: pnpm --filter @onelabs/kiosk test:e2e
